Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.define "master" do |node|
    node.vm.hostname = "master"
    node.vm.network "private_network", ip: "192.168.10.100"
  end

  config.vm.define "worker" do |node|
    node.vm.hostname = "worker"
    node.vm.network "private_network", ip: "192.168.10.101"
  end
end
