apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 172.16.0.100
      user: vagrant
      port: 22
      keyPath: /Users/kudaliar/.ssh/id_rsa
    role: controller
    privateInterface: enp0s8
  - ssh:
      address: 172.16.0.101
      user: vagrant
      port: 22
      keyPath: /Users/kudaliar/.ssh/id_rsa
    role: worker
    privateInterface: enp0s8
  - ssh:
      address: 172.16.0.102
      user: vagrant
      port: 22
      keyPath: /Users/kudaliar/.ssh/id_rsa
    role: worker
    privateInterface: enp0s8
  k0s:
    version: 1.22.2+k0s.0
