Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.define "master" do |node|
    node.vm.hostname = "master"
    node.vm.network "private_network", ip: "172.16.0.100"
  end

  (1..2).each do |i|
    config.vm.define "worker#{i}" do |node|
	  node.vm.hostname = "worker#{i}"
	  node.vm.network "private_network", ip: "172.16.0.10#{i}"
	end
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
	v.cpus = 2
  end
end
