Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"
	config.vm.box_check_update = false

	(1..4).each do |i|
		config.vm.define "k0s-multi-node#{i}" do |node|
			node.vm.hostname = "k0s-multi-node#{i}"
			node.vm.network "private_network", ip: "172.16.0.10#{i}"

			node.vm.provider "virtualbox" do |v|
				v.memory = 2048
				v.cpus = 2
			end
		end
	end
end

