---
- name: Install needed packages
  hosts: mycluster
  remote_user: vagrant
  gather_facts: no
  tasks:
  - name: Remove old docker version if availabe
    ansible.builtin.dnf:
      name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
      state: absent
    become: yes
  - name: Add docker repository
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    become: yes
  - name: Install docker engine
    ansible.builtin.dnf:
      name:
      - tmux
      - vim
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present
    become: yes
  - name: Enable docker engine
    ansible.builtin.service:
      name: docker.service
      state: started
      enabled: yes
    become: yes
