Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.provider("virtualbox") do |v|
      v.memory = 4096
      v.cpus = 2
    end
    master.vm.network "private_network", ip: "192.168.60.101"
  end

  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    worker.vm.provider("virtualbox") do |v|
      v.memory = 2048
      v.cpus = 1
    end
    worker.vm.network "private_network", ip: "192.168.60.102"
  end
end
