Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "web-server" do |node|
    node.vm.hostname = "web-server"
    #node.vm.network "public_network"
    node.vm.network "private_network", ip: "192.168.10.200"
  end

  (1..2).each do |i|
    config.vm.define "haproxy-#{i}" do |node|
      node.vm.hostname = "haproxy-#{i}"
      #node.vm.network "public_network"
      node.vm.network "private_network", ip: "192.168.10.10#{i}"
      node.vm.network "private_network", ip: "172.16.0.10#{i}"
    end
  end
end
