Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  config.vm.define "longhorn-instance-master" do |node|
    node.vm.hostname = "longhorn-instance-master"
    node.vm.network "private_network", ip: "172.16.0.100"
  end

  (1..3).each do |i|
    config.vm.define "longhorn-instance-worker#{i}" do |node|
      node.vm.hostname = "longhorn-instance-worker#{i}"
      node.vm.network "private_network", ip: "172.16.0.10#{i}"
    end
	end
end
