apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 172.17.0.101
      user: vagrant
      port: 22
      keyPath: /Users/kudaliar/.ssh/id_rsa
    role: controller
    privateInterface: enp0s8
  - ssh:
      address: 172.17.0.102
      user: vagrant
      port: 22
      keyPath: /Users/kudaliar/.ssh/id_rsa
    role: controller
    privateInterface: enp0s8
  - ssh:
      address: 172.17.0.103
      user: vagrant
      port: 22
      keyPath: /Users/kudaliar/.ssh/id_rsa
    role: controller
    privateInterface: enp0s8
  - ssh:
      address: 172.17.0.104
      user: vagrant
      port: 22
      keyPath: /Users/kudaliar/.ssh/id_rsa
    role: worker
    privateInterface: enp0s8
  k0s:
    version: 1.21.3+k0s.0
    config:
      spec:
        api:
          externalAddress: 172.17.0.100
          sans:
          - 172.17.0.100
