Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  (1..5).each do |i|
    config.vm.define "k0s-multi-master#{i}" do |node|
      node.vm.hostname = "k0s-multi-master#{i}"
      node.vm.network "private_network", ip: "172.17.0.10#{i}"
    end
  end
end

