Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"

	config.vm.network "private_network", ip: "172.16.0.101"

	config.vm.provider "virtualbox" do |v|
		v.name = "k0s-single-node"
		v.memory = 2048
		v.cpus = 2
	end
end
